name: dependencies
description: Collection of common project dependencies
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  cached_network_image: ^3.2.1
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  get_it: ^7.2.0
  intl: ^0.20.2
  shared_preferences: ^2.0.15
  fluttertoast: ^8.2.12
  web_socket_channel: ^3.0.3
  auto_size_text: ^3.0.0

  #domains
  commons_domain:
    path: ../../domains/commons_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
