name: resources
description: A resource module contains assets, images, and other resources stuff
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../../shared_libraries/dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_gen_runner: ^4.1.6
  flutter_lints: ^5.0.0

flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: id
  arb_dir: assets/localizations
  output_dir: lib/src/generated

flutter_gen:
  output: lib

  assets:
    package_parameter_enabled: true

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/main_color.xml

flutter:
  generate: true

  uses-material-design: true
