name: onboarding
description: A onboarding module features
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #shared
  common:
    path: ../../shared_libraries/common
  dependencies:
    path: ../../shared_libraries/dependencies

  #resource
  resources:
    path: ../../resources/resources

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
