name: component
description: A module about component of widget
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  resources:
    path: ../../resources/resources
  dependencies:
    path: ../dependencies
  common:
    path: ../common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
